import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import * as AdmZip from 'adm-zip';

@Injectable()
export class MarkdownVaultService {
  private readonly logger = new Logger(MarkdownVaultService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Generates a structured Obsidian-compatible Markdown Vault (.zip)
   * with conversation messages partitioned into monthly documents with frontmatter.
   */
  async generateMarkdownVault(datasetId: string): Promise<{ filename: string; buffer: Buffer }> {
    const dataset = await this.prisma.dataset.findUnique({
      where: { id: datasetId },
    });
    if (!dataset) {
      throw new NotFoundException(`Dataset ${datasetId} not found`);
    }

    const zip = new AdmZip();

    // 1. Fetch distinct months
    const events = await this.prisma.timelineEvent.findMany({
      where: { datasetId },
      select: {
        id: true,
        actor: true,
        timestamp: true,
        content: true,
        eventType: true,
      },
      orderBy: { timestamp: 'asc' },
    });

    // Group events by YYYY-MM
    const monthGroups = new Map<string, typeof events>();
    const actorsSet = new Set<string>();

    for (const ev of events) {
      if (ev.actor) actorsSet.add(ev.actor);
      const date = new Date(ev.timestamp);
      const monthKey = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
      const group = monthGroups.get(monthKey) || [];
      group.push(ev);
      monthGroups.set(monthKey, group);
    }

    // 2. Generate Root README.md in the Vault
    const readmeContent = `---
title: "${dataset.name} — Communication Archive"
source_type: "${dataset.sourceType}"
total_messages: ${events.length}
participants: [${Array.from(actorsSet).map((a) => `"${a}"`).join(', ')}]
exported_at: "${new Date().toISOString()}"
vault_generator: "Textboard v2.3"
---

# 📚 ${dataset.name} — Archive Vault

This vault was deterministically generated by **Textboard**.

- **Source Type**: \`${dataset.sourceType.toUpperCase()}\`
- **Total Records**: \`${events.length.toLocaleString()}\`
- **Active Months**: \`${monthGroups.size}\`
- **Participants**: ${Array.from(actorsSet).join(', ')}

## 🗂️ Monthly Archive Indices
${Array.from(monthGroups.keys())
  .map((m) => `- [[${m}|📅 Month ${m} (${monthGroups.get(m)?.length.toLocaleString()} messages)]]`)
  .join('\n')}
`;

    zip.addFile('README.md', Buffer.from(readmeContent, 'utf8'));

    // 3. Generate Monthly Markdown Files
    for (const [monthKey, monthEvents] of monthGroups.entries()) {
      let doc = `---
month: "${monthKey}"
dataset_id: "${dataset.id}"
dataset_name: "${dataset.name}"
message_count: ${monthEvents.length}
first_message: "${new Date(monthEvents[0].timestamp).toISOString()}"
last_message: "${new Date(monthEvents[monthEvents.length - 1].timestamp).toISOString()}"
tags:
  - communication-archive
  - textboard-vault
---

# 📅 Archive — ${monthKey}

*Total messages recorded in this interval: ${monthEvents.length.toLocaleString()}*

---

`;

      let lastDateStr = '';

      for (const ev of monthEvents) {
        const evDate = new Date(ev.timestamp);
        const curDateStr = evDate.toLocaleDateString();

        if (curDateStr !== lastDateStr) {
          doc += `\n### 🗓️ ${curDateStr}\n\n`;
          lastDateStr = curDateStr;
        }

        const timeStr = evDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
        const actorStr = ev.actor || 'System';

        doc += `> **${actorStr}** \`[${timeStr}]\`\n>\n> ${ev.content.replace(/\n/g, '\n> ')}\n\n`;
      }

      zip.addFile(`${monthKey}.md`, Buffer.from(doc, 'utf8'));
    }

    const zipBuffer = zip.toBuffer();
    const filename = `${dataset.name.replace(/[^a-zA-Z0-9_-]/g, '_')}_Markdown_Vault.zip`;

    return {
      filename,
      buffer: zipBuffer,
    };
  }
}
