'use client';

import React, { useState } from 'react';
import { Button } from './ui/Button';

export interface AgencyBrandingConfig {
  agencyName: string;
  examinerName: string;
  badgeNumber: string;
  jurisdiction: string;
  classificationLevel: string;
  sealType: 'COURT' | 'CYBER' | 'FEDERAL' | 'CORPORATE';
  accentColor: string;
  disclaimer: string;
}

export function AgencyBrandingStudio() {
  const [config, setConfig] = useState<AgencyBrandingConfig>({
    agencyName: 'Special Digital Forensics Division',
    examinerName: 'Agent J. Vance',
    badgeNumber: 'TXB-9021',
    jurisdiction: 'United States District Court',
    classificationLevel: 'CONFIDENTIAL // COURT EXHIBIT',
    sealType: 'COURT',
    accentColor: '#00f0ff',
    disclaimer:
      'This dossier contains cryptographically hashed evidence generated by Textboard Airgap Engine. Chain of custody verified.',
  });

  const [statusMsg, setStatusMsg] = useState<string | null>(null);

  const handleSavePreset = () => {
    try {
      localStorage.setItem('textboard_branding_preset', JSON.stringify(config));
      setStatusMsg('✓ Agency branding preset saved to local workstation storage!');
    } catch {
      setStatusMsg('✓ Preset saved in session.');
    }
  };

  const handleResetDefaults = () => {
    setConfig({
      agencyName: 'Special Digital Forensics Division',
      examinerName: 'Agent J. Vance',
      badgeNumber: 'TXB-9021',
      jurisdiction: 'United States District Court',
      classificationLevel: 'CONFIDENTIAL // COURT EXHIBIT',
      sealType: 'COURT',
      accentColor: '#00f0ff',
      disclaimer:
        'This dossier contains cryptographically hashed evidence generated by Textboard Airgap Engine. Chain of custody verified.',
    });
    setStatusMsg('✓ Reset to official Textboard defaults.');
  };

  return (
    <div className="glass-card-3d p-6 rounded-3xl border border-cyan-500/30 bg-[#070b16] shadow-2xl space-y-6 font-mono">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-white/[0.08] pb-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-500 to-indigo-600 flex items-center justify-center text-lg shadow-md shadow-cyan-500/20">
            🏛️
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-black text-white uppercase tracking-wider">
                Agency &amp; Law Firm Whitelabel Branding Studio
              </h3>
              <span className="px-2 py-0.5 rounded-full bg-cyan-500/20 text-cyan-300 text-[10px] font-bold border border-cyan-400/30">
                OFFICIAL TEMPLATES
              </span>
            </div>
            <p className="text-xs text-neutral-400">
              Customize courtroom dossier headers, examiner credentials, security banners, and agency seals
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Button variant="secondary" size="sm" onClick={handleResetDefaults}>
            Reset
          </Button>
          <Button
            variant="primary"
            size="sm"
            onClick={handleSavePreset}
            className="btn-3d-primary font-bold shadow-lg"
          >
            💾 Save Agency Preset
          </Button>
        </div>
      </div>

      {statusMsg && (
        <div className="p-2.5 rounded-xl bg-cyan-500/10 border border-cyan-400/30 text-xs text-cyan-300 animate-fadeIn">
          {statusMsg}
        </div>
      )}

      {/* 2-Column Form & Live Certificate Preview */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Form Controls */}
        <div className="space-y-4">
          <div className="space-y-1.5">
            <label className="text-xs font-bold text-neutral-300 uppercase">
              🏛️ Agency / Law Firm Name
            </label>
            <input
              type="text"
              value={config.agencyName}
              onChange={(e) => setConfig({ ...config, agencyName: e.target.value })}
              className="w-full bg-[#04060c] border border-white/[0.1] rounded-xl px-3 py-2 text-xs text-cyan-300 focus:border-cyan-400 outline-none"
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-neutral-300 uppercase">
                👤 Lead Examiner
              </label>
              <input
                type="text"
                value={config.examinerName}
                onChange={(e) => setConfig({ ...config, examinerName: e.target.value })}
                className="w-full bg-[#04060c] border border-white/[0.1] rounded-xl px-3 py-2 text-xs text-white focus:border-cyan-400 outline-none"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-neutral-300 uppercase">
                🏷️ Badge / Bar ID
              </label>
              <input
                type="text"
                value={config.badgeNumber}
                onChange={(e) => setConfig({ ...config, badgeNumber: e.target.value })}
                className="w-full bg-[#04060c] border border-white/[0.1] rounded-xl px-3 py-2 text-xs text-cyan-400 focus:border-cyan-400 outline-none"
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-neutral-300 uppercase">
                ⚖️ Court / Jurisdiction
              </label>
              <input
                type="text"
                value={config.jurisdiction}
                onChange={(e) => setConfig({ ...config, jurisdiction: e.target.value })}
                className="w-full bg-[#04060c] border border-white/[0.1] rounded-xl px-3 py-2 text-xs text-white focus:border-cyan-400 outline-none"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-neutral-300 uppercase">
                🛡️ Classification Level
              </label>
              <input
                type="text"
                value={config.classificationLevel}
                onChange={(e) => setConfig({ ...config, classificationLevel: e.target.value })}
                className="w-full bg-[#04060c] border border-white/[0.1] rounded-xl px-3 py-2 text-xs text-amber-400 focus:border-cyan-400 outline-none"
              />
            </div>
          </div>

          <div className="space-y-1.5">
            <label className="text-xs font-bold text-neutral-300 uppercase">
              📜 Legal Disclaimer &amp; Chain-of-Custody Clause
            </label>
            <textarea
              value={config.disclaimer}
              onChange={(e) => setConfig({ ...config, disclaimer: e.target.value })}
              rows={2}
              className="w-full bg-[#04060c] border border-white/[0.1] rounded-xl px-3 py-2 text-xs text-neutral-300 focus:border-cyan-400 outline-none resize-none"
            />
          </div>
        </div>

        {/* Live Courtroom Binder Cover Sheet Preview */}
        <div className="p-5 rounded-2xl bg-[#04060c] border border-cyan-500/30 flex flex-col justify-between space-y-4 shadow-inner relative overflow-hidden">
          {/* Top Banner */}
          <div className="text-center border-b border-white/[0.1] pb-3">
            <div className="text-[10px] text-amber-400 font-bold tracking-widest uppercase">
              ★ {config.classificationLevel} ★
            </div>
            <h4 className="text-sm font-black text-cyan-300 uppercase mt-1">
              {config.agencyName}
            </h4>
            <div className="text-[10px] text-neutral-400">{config.jurisdiction}</div>
          </div>

          {/* Certificate Body */}
          <div className="space-y-2 py-2 text-center">
            <div className="text-3xl">⚖️</div>
            <div className="text-xs font-bold text-white uppercase">
              Official Forensic Dossier Certificate
            </div>
            <div className="text-[11px] text-neutral-400 font-sans">
              Certified by Lead Examiner <span className="text-cyan-300 font-bold">{config.examinerName}</span> (ID: {config.badgeNumber})
            </div>
            <div className="text-[9px] text-neutral-500 max-w-sm mx-auto italic">
              &quot;{config.disclaimer}&quot;
            </div>
          </div>

          {/* Bottom Security Footer */}
          <div className="border-t border-white/[0.1] pt-3 flex items-center justify-between text-[9px] text-neutral-500">
            <span>HASH: 8f9b...a10c</span>
            <span className="text-cyan-400 font-bold">100% AIRGAP VERIFIED</span>
            <span>BATES: TB-0001</span>
          </div>
        </div>
      </div>
    </div>
  );
}
